# Generated by Django 3.0.5 on 2021-06-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210606_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category',
                     'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'genre',
                     'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('name',), 'verbose_name': 'title',
                     'verbose_name_plural': 'titles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': (
                'username',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
