# Generated by Django 3.0.5 on 2021-06-08 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210608_1915'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='A score value is valid between 1 and 10',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(
                1), django.core.validators.MaxValueValidator(10)], verbose_name='score'),
        ),
    ]
