# Generated by Django 3.0.5 on 2021-06-08 19:45

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210608_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      api.validators.custom_year_validator], verbose_name='year'),
        ),
    ]
